version: '3.8'

services:
  vite_docker:
    container_name: harry-potter-microfrontend-container
    entrypoint: /bin/sh
    image: node:alpine
    volumes:
      - .:/app
    tty: true
    ports:
      - 3006:3006
    working_dir: /app
