version: '3.8'

services:
  app:
    container_name: harry-potter-microfrontend-container
    image: harry-potter-microfrontend-container
    environment:
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3006:3006
